export const data = [
  {
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    genre: "Fiction",
    year: 1925,
    status: "Available",
  },
  {
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    genre: "Drama",
    year: 1960,
    status: "Issued",
  },
  {
    title: "1984",
    author: "George Orwell",
    genre: "Sci-Fi",
    year: 1949,
    status: "Available",
  },
  {
    title: "Pride and Prejudice",
    author: "Jane Austen",
    genre: "Romance",
    year: 1813,
    status: "Available",
  },
  {
    title: "Moby-Dick",
    author: "Herman Melville",
    genre: "Adventure",
    year: 1851,
    status: "Issued",
  },
  {
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    genre: "Fantasy",
    year: 1937,
    status: "Available",
  },
  {
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    genre: "Fiction",
    year: 1951,
    status: "Available",
  },
  {
    title: "Brave New World",
    author: "Aldous Huxley",
    genre: "Sci-Fi",
    year: 1932,
    status: "Issued",
  },
  {
    title: "War and Peace",
    author: "Leo Tolstoy",
    genre: "Historical",
    year: 1869,
    status: "Available",
  },
  {
    title: "The Alchemist",
    author: "Paulo Coelho",
    genre: "Philosophy",
    year: 1988,
    status: "Available",
  },
  {
    title: "Crime and Punishment",
    author: "Fyodor Dostoevsky",
    genre: "Drama",
    year: 1866,
    status: "Issued",
  },
  {
    title: "Harry Potter and the Sorcerer's Stone",
    author: "J.K. Rowling",
    genre: "Fantasy",
    year: 1997,
    status: "Available",
  },
  {
    title: "The Lord of the Rings",
    author: "J.R.R. Tolkien",
    genre: "Fantasy",
    year: 1954,
    status: "Issued",
  },
  {
    title: "Don Quixote",
    author: "Miguel de Cervantes",
    genre: "Adventure",
    year: 1605,
    status: "Available",
  },
  {
    title: "Meditations",
    author: "Marcus Aurelius",
    genre: "Philosophy",
    year: 180,
    status: "Available",
  },
];

export const genres = [
  "Fiction",
  "Drama",
  "Sci-Fi",
  "Romance",
  "Adventure",
  "Fantasy",
  "Historical",
  "Philosophy",
];
